import json
import os
from google_auth_oauthlib.flow import InstalledAppFlow

# Constants from config and user input
creds_path = '/home/ubuntu/credentials.json'
token_path = '/home/ubuntu/token.json'
code = '4/0AfrIepCHRWFMto_qor9SwmSBe8RjgnQO5utEY0PCOAA3m6MiHSoxRqsSXIz1zKY3bywe1g'
# Using the redirect URI that matches the original request
redirect_uri = 'http://localhost:41595/'

def exchange():
    flow = InstalledAppFlow.from_client_secrets_file(
        creds_path,
        scopes=['https://www.googleapis.com/auth/gmail.readonly'],
        redirect_uri=redirect_uri
    )
    
    # We don't have the original code_verifier here if it was generated by another flow,
    # but since the user provided the full URL from the previous attempt, we'll try to fetch the token.
    # If the flow was initialized in the previous turn by 'run_local_server', the session might be lost.
    # However, we can try to exchange it.
    
    try:
        flow.fetch_token(code=code)
        creds = flow.credentials
        
        with open(token_path, 'w') as token:
            token.write(creds.to_json())
        print(f"Token successfully saved to {token_path}")
    except Exception as e:
        print(f"Error exchanging code: {e}")

if __name__ == "__main__":
    exchange()
